# Auto-generated by Android Gradle plugin
-dontwarn org.tensorflow.lite.gpu.GpuDelegateFactory$Options

# TensorFlow Lite GPU
-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.gpu.** { *; }
-dontwarn org.tensorflow.lite.**

# ML Kit
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**
